### ISSUE TITLE
Possible broken docstring

### ISSUE THREAD

**Issue by wittregr** [VlachosGroup/PyMuTT#14]
When fixing a long line I needed to break a number of these into two lines.

.. _`numpy.ndarray`: https://docs.scipy.org/doc/numpy-1.14.0/reference/
                                     generated/numpy.ndarray.html

This might break how Sphinx uses this mark-up

**Comment by jonlym** [comment]
So the hyperlink goes over two lines? Normally Sphinx doesn't have a problem if you're breaking up a sentence over multiple lines but I think it will affect a hyperlink.

**Comment by jonlym** [comment]
Confirmed that breaking up links in multiple lines breaks the link. All links will be left on one line even if it goes over the 80 characters per line limit.
