### ISSUE TITLE
Sphinx for documentation

### ISSUE THREAD

**Issue by jonlym** [VlachosGroup/PyMuTT#6]
Should Sphinx be used for documentation instead of Python docstrings? It may make it easier for others to become familiar with the library.

**Comment by mpnunez** [comment]
Let me know if you need any help using Sphynx (and interfacing it with Github). Also, [Jupyter notebooks](http://jupyter.org/) are great for documenting examples for how to use the code. It's easy to use from Anaconda on your desktop and can be exported in many formats (including .rst which is used in Sphynx).

**Comment by jonlym** [comment]
Thanks, @mpnunez! I'll also see if I can find your WebEx tutorial on it.

**Comment by jonlym** [comment]
@mpnunez 
I noticed the Zacros wrapper's documentation is hosted by Github (URL format of [username].github.io seems to match the instructions given on the [Github Pages site](https://pages.github.com/)). I want to clone the repository to add PyMuTT's documentation but I can't find the VlachosGroup.github.io repository online. Do you know how I can access it? If I try to create a new one with that name, will it delete your Zacros documentation?

**Comment by mpnunez** [comment]
I am not sure what repository you are trying to clone. There is no VlachosGroup.github.io repository. What you are supposed to clone is the Pymutt repository into a separate folder called html. See "Set up separate docs repository" [here](https://daler.github.io/sphinxdoc-test/includeme.html). You follow the steps on that website to set up the gh-pages branch, then push it to the remote (Github). Once Github recognizes that there is a gh-pages branch, "gh-pages branch" will appear in the dropdown menu in the repository [settings page](https://github.com/VlachosGroup/PyMuTT/settings) under Github Pages -> Source.

Fill that folder with the gh-pages branch with your documentation (rst files I think). When you commit and push it should build your documentation with sphynx on some remote server and webhost it.

Don't worry about overwriting the ZacrosWrapper Github page. By default, it will name your website http://vlachosgroup.github.io/PyMuTT/. Once you have a website, a "custom domain" field will appear in the Github Pages section of the repository settings.

To clarify, this is setting up the PyMuTT documentation as a separate website than the ZacrosWrapper, which is simplest. 1 website per repository. It would get confusing if you tried to combine them (you would have to add your documentation to the gh-pages branch of ZacrosWrapper), and you can always just add links to each other.

I hope that answers your questions. Let me know if there is confusion. I can talk on the phone if needed. I've been meaning to get around to cleaning up some of the ZacrosWrapper stuff anyway.

**Comment by jonlym** [comment]
Documentation was built using the above instructions and can be found at [https://vlachosgroup.github.io/PyMuTT/](https://vlachosgroup.github.io/PyMuTT/). Currently, only the docstrings are available. We still need to merge the Wiki documents into the Sphinx website in a coherent way.
